# Generated by Django 3.2 on 2021-04-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_accounts_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
    ]
