# Generated by Django 3.2 on 2021-04-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_accounts_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0, null=True),
        ),
    ]
