# Generated by Django 3.2 on 2021-04-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20210430_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='updateAt',
            field=models.DateTimeField(null=True),
        ),
    ]
