# Generated by Django 3.2 on 2021-05-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='public_id',
            field=models.CharField(default='3e2339ee-c4dc-4991-8a24-8fdc81e4421e', max_length=225, unique=True),
        ),
    ]
