# Generated by Django 3.2 on 2021-05-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20210501_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='f6bb8e33-33ba-4d14-98a2-0eed01f34439', max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='public_id',
            field=models.CharField(default='5b921b9c-114b-44c5-8f8e-768af5c93f99', max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='public_id',
            field=models.CharField(default='695d6c55-6f04-4b5f-8a8d-3a9ffdb28939', max_length=225, unique=True),
        ),
    ]
